### ISSUE TITLE
Scipp will probably use LLNL/units

### ISSUE THREAD

**Issue by SimonHeybrock** [LLNL/units#108]
Hi!
I just wanted to get in touch to let you know that [scipp](https://scipp.github.io/) is probably going to use this library. Scipp is a Python/C++ library for neutron-scattering developed by the European Spallation Source. We have been looking for a better way to handle units, and so far `LLNL/units` seems to check all the boxes. 👍 

We will probably have a couple of questions, issues, or maybe pull-requests soon.

Cheers,
Simon

**Comment by phlptp** [comment]
happy to help

**Comment by SimonHeybrock** [comment]
One of our unit tests tripped over the way "angstrom" is formatted. We had previously used [Angstrom Sign](https://www.compart.com/en/unicode/U+212B), but `units` used [Latin Capital Letter A with Ring Above](https://www.compart.com/en/unicode/U+00C5). Not a big problem (I think), but is there a reason behind this choice?

**Comment by phlptp** [comment]
Not really.  If there is a better symbol to use, would be happy to make the change.  Angstrom isn't used very commonly in the fields I work in.

**Comment by SimonHeybrock** [comment]
Honestly I don't know if one is better than the other. My only indicator was that googling for "angstrom unicode" gives the other one.

**Comment by i-ky** [comment]
Wikipedia [mentions](https://en.wikipedia.org/wiki/Unicode_equivalence#Character_duplication) these two characters as an example of "canonical equivalence". This means that they both should be treated equally and either of them can be used with the same meaning.

**Comment by SimonHeybrock** [comment]
This has been part of scipp since the 0.6 release in March and works very well so far. Thanks a lot for this library and for your support!

**Comment by phlptp** [comment]
Thanks for all the suggestions and PR's!
