### ISSUE TITLE
Cannot parse some unit strings from `scipy.constants`

### ISSUE THREAD

**Issue by SimonHeybrock** [LLNL/units#163]
Example: `J mol^-1 K^-1` (the unit of `R`, the gas constant).

It works if I replace the first space by a `*`.

**Comment by SimonHeybrock** [comment]
Here is a full list of the constants defined in [scipy.constants](https://docs.scipy.org/doc//scipy-1.4.0/reference/constants.html#scipy.constants.physical_constants) (same as https://physics.nist.gov/cuu/Constants/Table/allascii.txt) that cannot be parsed (I give the unit in square brackets):

```
atomic mass unit-hartree relationship [E_h]
electron volt-hartree relationship [E_h]
Faraday constant for conventional electric current [C_90 mol^-1]
hertz-hartree relationship [E_h]
inverse meter-hartree relationship [E_h]
joule-hartree relationship [E_h]
kelvin-hartree relationship [E_h]
kilogram-hartree relationship [E_h]
natural unit of momentum in MeV/c [MeV/c]
Newtonian constant of gravitation over h-bar c [(GeV/c^2)^-2]
natural unit of mom.um in MeV/c [MeV/c]
```

**Comment by phlptp** [comment]
I will work on adding support for those

**Comment by phlptp** [comment]
Added E_h and support for conventional electrical units.    The units with 'c' in them I am still debating what to do.  

also fixed `J mol^-1 K^-1`

**Comment by phlptp** [comment]
ok,  I am going to add a `UNIT_USE_COOKING_UNITS` flag which would shift some units to the cooking abbreviations but default to the science units.  This enables the use of 'c' as the speed of light, which I think should fix your issues.    Need to do a bit more testing and add the docs but I should have a PR by Monday
