### ISSUE TITLE
Convert to inverse unit incorrect

### ISSUE THREAD

**Issue by Gra-tak** [LLNL/units#165]
Thanks for this awesome library. As far as I can tell, I have found an error in the conversion between inverse magnitudes like Hertz and seconds.
``` 
units::precise_unit unitA=units::unit_from_string("ms");
units::precise_unit unitB=units::unit_from_string("kHz");
double v=units::convert(1, unitA, unitB);
double v2=units::convert(v, unitB, unitA);
std::cout << "v = '" << v << "'" << std::endl;
std::cout << "v2 = '" << v2 << "'" << std::endl;
```
gives the following output:
```
v = '1e+06'
v2 = '1e-12'
```

As far as I can tell, 
`return result.multiplier() / (val * start.multiplier());`
should be replaced by 
`1.0 / (val * start.multiplier() * result.multiplier());`.

**Comment by phlptp** [comment]
You are correct.  I had never tested that code path with both units having multipliers.  
Added some tests and fixed the issue in #166 

Thanks for catching that.
