### ISSUE TITLE
Format arbitrary unit nicely

### ISSUE THREAD

**Issue by jl-wynen** [LLNL/units#268]
Currently, the following
```cpp
auto u = units::unit_from_string("arbitraryunit");
std::cout << to_string(u) << '\n';
```
prints `CXCUN[1]`. It would be nice if it printed `arbitraryunit` or something along those lines.

**Comment by phlptp** [comment]
There are a lot of units that can be converted from a string but aren't displayed in an equivalent fashion.  

addUserDefinedUnit("arbitraryunit", units::unit_from_string("arbitraryunit"));

should work, or whatever string you do, though that particular piece of code would only work once.  

I am also thinking to add an `addUserDefinedOutputUnit` for cases like this as well in the near future.

**Comment by jl-wynen** [comment]
Ok. Maybe I'm biased because arbitrary unit is relatively important for us.
We have our own mechanism for handling user defined units as mentioned in #271. I opened this issue because we would prefer to avoid adding special handling to always enforce a certain formatting of `CXCUN[1]`. But I see your point

**Comment by phlptp** [comment]
Fair enough,  easy enough to add output units like this in the tables for units that don't interfere with existing ones.  Feel free to make a PR adding it, or just let me know what string you want and I will add it next I am tinkering with that part of the code.    It would go in `defined_unit_names_si`  then you just have to adjust the array size.
