### ISSUE TITLE
Try to start a PR for adding support for KPa, MPa, GPa but permission denied

### ISSUE THREAD

**Issue by ruihuasun** [LLNL/units#281]
Like the title says.

**Comment by phlptp** [comment]
How are you trying this, there should be no restrictions on creating a PR from a fork.  
And what isn't working in regard to those units.  MPa and GPa should be pretty standard SI prefixes to Pascals

**Comment by ruihuasun** [comment]
@phlptp Sorry for this unnecessary issue. Cool for SI prefixes. I didn't see GPa in the help, so I thought it didn't support GPa,...

**Comment by phlptp** [comment]
The library should support nearly all units I can find reference to and all SI prefixes,  But if you find one that doesn't feel free to add it or let me know.
