### ISSUE TITLE
Using to_string for scalars causes crashes

### ISSUE THREAD

**Issue by afoolsbag** [LLNL/units#288]
In function

https://github.com/LLNL/units/blob/e5b5765b553077c645fada9553b7f4078d87319e/units/units.cpp#L1723-L1736

the call

```C++
        auto str = to_string(measure.units(), match_flags);
```

may return an empty string.

This will cause a crash when using `str.front()`.

**Comment by phlptp** [comment]
thanks I will look into it

**Comment by phlptp** [comment]
Fixed,  Thanks!
