### ISSUE TITLE
to_string strange output

### ISSUE THREAD

**Issue by StrikeByte** [LLNL/units#307]
to_string does not output the expected unit when using mm/s or mm/s^2 as a unit
see the example below

`auto speedUnit = unit_from_string("mm/s");
cout << "speed unit" << to_string(speedUnit); //outputs mHz*m
auto accUnit = unit_from_string("mm/s^2");
cout << "acceleration unit" << to_string(accUnit); //outputs 1/um`

the webconverter does the same when pressing to_string, pressing convert will produce the right string representation

**Comment by SimonHeybrock** [comment]
@phlptp Could this have been broken by #303? I don't see the problem with an older release.

**Comment by StrikeByte** [comment]
I changed to commit #300 there the mm/s seems to work but I still have an issue with acceleration mm/s^2
auto accUnit = unit_from_string("mm/s^2");
cout << "acc unit" << to_string(accUnit); //prints "Gy/km"

auto accUnit = lengthUnit / (timeUnit * timeUnit);
cout << "accUnit" << to_string(accUnit); //also prints "Gy/km"

**Comment by StrikeByte** [comment]
Wow thats fast great work! The fix seems to be working.

**Comment by SimonHeybrock** [comment]
@phlptp Thanks! Could we get a patch release for this?
