### ISSUE TITLE
come across compile error, if include Windows.h before units.hpp

### ISSUE THREAD

**Issue by fengfengguo** [LLNL/units#344]
When I include Windows.h and units.hpp in a *.cpp, but Windows.h above units.hpp
like
![image](https://github.com/user-attachments/assets/c8d9c7a0-8a72-4f82-839b-fee9ca6de1c3)

then come across compile errors
![image](https://github.com/user-attachments/assets/4e741580-0c3c-40c6-8a73-abf1804052a9)
 
maybe the definition for time or min conflicts with some define in Windows

please help to resolve the problem, Thanks!

**Comment by phlptp** [comment]
I think the issue has been resolved in the main branch. I added a test and some fixes.  The min unit identifier has been removed.  Along with pascal and IN   still not sure where those were coming from but they had the same issue as min when default windows.h was included.

**Comment by fengfengguo** [comment]
thanks very much for the solution！

> I think the issue has been resolved in the main branch. I added a test and some fixes. The min unit identifier has been removed. Along with pascal and IN still not sure where those were coming from but they had the same issue as min when default windows.h was included.
