### ISSUE TITLE
"Pounds" not recognized consistently during case-insensitive string conversions

### ISSUE THREAD

**Issue by DragoonBoots** [LLNL/units#90]
When performing string conversions, `"lb"` and `"lbs"` are recognized differently depending on the `units::case_insensitive` flag. 
 I've tested this behavior using the latest commit in master (2c68c59).

Both `"lb"` and `"lbs"` result in a measurement with unit `units::lb` without the `units::case_insensitive` flag.  However, only `"lbs"` is recognized with the flag.  `"lb"` results in an invalid unit.

This can wreak extra havoc when round-tripping through a string because the unit abbreviation is normalized to `"lb"`.  I use the same function in a wrapper class to take input from the user and from a SQLite database; this function must allow case-insensitive parsing as input comes from untrained users in a GUI.  As a workaround, I can force case-sensitive parsing when coming from the database, but the inconsistent behavior seems buggy and I'd rather not need two separate `FromString()` methods in my wrapper class.

Below is a short example program to demonstrate this behavior:

```c++
#include <units/units.hpp>
#include <iostream>

int main() {
  // Case sensitive string conversion
  units::precise_measurement case_sensitive_plural =
      units::measurement_from_string("17 lbs");
  // true
  std::cout << "case sensitive plural: " << case_sensitive_plural.units().has_same_base(units::lb) << std::endl;
  units::precise_measurement case_sensitive_singular =
      units::measurement_from_string("17 lb");
  // true
  std::cout << "case sensitive singular: " << case_sensitive_singular.units().has_same_base(units::lb) << std::endl;

  // Case insensitive string conversion
  units::precise_measurement case_insensitive_plural =
      units::measurement_from_string("17 lbs", units::case_insensitive);
  // true
  std::cout << "case insensitive plural: " << case_insensitive_plural.units().has_same_base(units::lb) << std::endl;
  units::precise_measurement case_insensitive_singular =
      units::measurement_from_string("17 lb", units::case_insensitive);
  // false
  std::cout << "case insensitive singular: " << case_insensitive_singular.units().has_same_base(units::lb) << std::endl;

  // Round trip
  const std::string case_insensitive_plural_str = units::to_string(case_insensitive_plural);
  units::precise_measurement round_trip =
      units::measurement_from_string(case_insensitive_plural_str, units::case_insensitive);
  // false
  std::cout << "round trip: " << round_trip.units().has_same_base(units::lb) << std::endl;

  return 0;
}
```

This creates the following output:
```
case sensitive plural: 1
case sensitive singular: 1
case insensitive plural: 1
case insensitive singular: 0
round trip: 0
```

**Comment by phlptp** [comment]
That does sound like a bug,  I will take a look.  Would you mind if I used that example program as part of a test case?

**Comment by DragoonBoots** [comment]
Go right ahead!  I only wrote it to rule out any funny business in my wrapper, but haven't checked any units other than pounds.

**Comment by phlptp** [comment]
Looks like the bug applied to two character units that are commonly/occasionally plural, So I have fixed it for lb, yd, oz, qt.  and am checking for any others that might fit in that category.  The reason being testing changed case with two characters ends up in a lot of false positive unit conversions so it isn't done for 2 or fewer characters.  So with plural form it worked fine since it was 3 characters.    I will get a pull request merged in the next day which resolves it for the identified units.  

Thanks!

**Comment by phlptp** [comment]
This should be working in master now

**Comment by DragoonBoots** [comment]
Looks like it's working now.  Thanks for the quick fix!
